# Generated by Django 2.2.3 on 2019-12-08 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airport_id', models.CharField(max_length=10, unique=True)),
                ('Airport_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_no', models.IntegerField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='users.Airport')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='users.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_passengers', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Flights')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
